environment:
  matrix:
    - nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - tsc -p tsconfig.json
  - jest --coverage

build: off
